[olricd]
partitionCount = 19
backupCount = 0
backupMode = 0
name = "0.0.0.0:3320"
tcpAddr = "0.0.0.0:3422"
certFile = ""
keyFile = ""
serializer = "msgpack"
keepAlivePeriod = "300s"

[snapshot]
enabled = false
dir = "/home/burak/olricd-data"
interval = "1s"
gcInterval  = "5m"
gcDiscardRatio = 0.7

[logging]
level = "DEBUG"
output = "stderr"

[memberlist]
environment = "local"
addr = "0.0.0.0:3322"
enableCompression = false
peers = [
  "localhost:3325"
]

#[cache]
#maxIdleDuration = ""
#ttlDuration = "100s"
#maxKeys = 100000
#lRUSamples = 10
#evictionPolicy = "LRU"

[dmaps]
[dmaps.foobar]
maxIdleDuration = "60s"
#ttlDuration = "300s"
#maxKeys = 500000
#lRUSamples = 20
#evictionPolicy = "NONE"

